[package]
name = "comfywm"
description = "..."
version = "0.1.0"
documentation = "..."
homepage = "..."
repository = "..."
authors = ["dubd2206 <daniel-junior.dube@usherbrooke.ca>", "chaf2717 <felix.chabot@usherbrooke.ca>"]
build = "build.rs"
readme = "README.md"
license-file = "LICENSE"
keywords = ["window managers", "desktop", "wm", "linux", "interface"]
categories = ["os"]

[dependencies]
wlroots = { path = "./lib/wlroots-rs" }
libc = "0.2.43"
