[package]
name = "comfywm"
description = "..."
version = "0.1.0"
documentation = "..."
homepage = "..."
repository = "..."
authors = ["dubd2206 <daniel-junior.dube@usherbrooke.ca>", "chaf2717 <felix.chabot@usherbrooke.ca>"]
edition = "2018"
keywords = ["window managers", "desktop", "wm", "linux", "interface"]
categories = ["os"]
readme = "README.md"
license-file = "LICENSE"

[dependencies]
# Using nightly since the stable version is temporarily unavailable
rustfmt-nightly = "0.99.4"
wlroots = { path = "./lib/wlroots-rs" }
