#..####...##..##..######..#####...##...##..#####...######..######..######.
#.##..##..##..##..##......##..##..##...##..##..##....##......##....##.....
#.##..##..##..##..####....#####...##.#.##..#####.....##......##....####...
#.##..##...####...##......##..##..#######..##..##....##......##....##.....
#..####.....##....######..##..##...##.##...##..##..######....##....######.
#.........................................................................

# Overwrite the default broken task 'format-stable'
[tasks.format-stable]
install_crate = "rustfmt"
command = "cargo"
args = ["fmt", "--", "--check"]


#.######..##..##..######..######.
#...##....###.##....##......##...
#...##....##.###....##......##...
#...##....##..##....##......##...
#.######..##..##..######....##...
#................................

# Init/updates git submodules recursively
[tasks.init-git-submodules]
command = "git"
args = ["submodule", "update", "--init", "--recursive"]

# Initialize the development environment
[tasks.init-dev]
dependencies = [
	"init-git-submodules"
]

#.#####...##..##..##..##.
#.##..##..##..##..###.##.
#.#####...##..##..##.###.
#.##..##..##..##..##..##.
#.##..##...####...##..##.
#........................

# Runs the developpment environment with debug logs
[tasks.run-dev]
env = { RUST_LOG = "comfy=debug" }
command = "cargo"
args = ["run"]

#.#####...##..##..######..##......#####..
#.##..##..##..##....##....##......##..##.
#.#####...##..##....##....##......##..##.
#.##..##..##..##....##....##......##..##.
#.#####....####...######..######..#####..
#........................................

# Builds the release version of the binary
[tasks.build-release]
command = "cargo"
args = ["build", "--release"]

# Set or update the desktop entry
[tasks.update-desktop-entry]
command = "cp"
args = ["./data/comfy.desktop", "/usr/share/wayland-sessions/"]

# Set or update the desktop entry
[tasks.build-release-and-copy-to-bin]
command = "cp"
args = ["./target/release/comfywm", "/bin/comfywm"]
dependencies = [
	"build-release"
]

#.######..##..##...####...######...####...##......##.....
#...##....###.##..##........##....##..##..##......##.....
#...##....##.###...####.....##....######..##......##.....
#...##....##..##......##....##....##..##..##......##.....
#.######..##..##...####.....##....##..##..######..######.
#........................................................

# Builds and installs the comfy window manager on the local system
[tasks.install]
command = "echo"
args = ["All done!"]
dependencies = [
	"build-release-and-copy-to-bin",
	"update-desktop-entry",
]

#.#####...######..#####...##.......####...##..##.
#.##..##..##......##..##..##......##..##...####..
#.##..##..####....#####...##......##..##....##...
#.##..##..##......##......##......##..##....##...
#.#####...######..##......######...####.....##...
#................................................

# Updates the latest release binary
[tasks.deploy]
command = "echo"
args = ["TODO!"]