#..####...##..##..######..#####...##...##..#####...######..######..######.
#.##..##..##..##..##......##..##..##...##..##..##....##......##....##.....
#.##..##..##..##..####....#####...##.#.##..#####.....##......##....####...
#.##..##...####...##......##..##..#######..##..##....##......##....##.....
#..####.....##....######..##..##...##.##...##..##..######....##....######.
#.........................................................................

# Overwrite the default broken task 'format-stable'
[tasks.format-stable]
install_crate = "rustfmt"
command = "cargo"
args = ["fmt", "--", "--check"]


#.######..##..##..######..######.
#...##....###.##....##......##...
#...##....##.###....##......##...
#...##....##..##....##......##...
#.######..##..##..######....##...
#................................

# Init/updates git submodules recursively
[tasks.init-git-submodules]
command = "git"
args = ["submodule", "update", "--init", "--recursive"]

# Initialize the development environment
[tasks.init-dev]
dependencies = [
	"init-git-submodules"
]

#.#####...##..##..##..##.
#.##..##..##..##..###.##.
#.#####...##..##..##.###.
#.##..##..##..##..##..##.
#.##..##...####...##..##.
#........................

# Runs the developpment environment with debug logs
[tasks.run-dev]
env = { RUST_LOG = "comfy=debug" }
command = "cargo"
args = ["run"]

#.######..##..##...####...######...####...##......##.....
#...##....###.##..##........##....##..##..##......##.....
#...##....##.###...####.....##....######..##......##.....
#...##....##..##......##....##....##..##..##......##.....
#.######..##..##...####.....##....##..##..######..######.
#........................................................

# Builds and installs the comfy window manager on the local system
[tasks.install]
command = "echo"
args = ["TODO!"]

#.#####...######..#####...##.......####...##..##.
#.##..##..##......##..##..##......##..##...####..
#.##..##..####....#####...##......##..##....##...
#.##..##..##......##......##......##..##....##...
#.#####...######..##......######...####.....##...
#................................................

# Updates the latest release binary
[tasks.deploy]
command = "echo"
args = ["TODO!"]