# This config uses TOML.
# Please refer to their documentation for more details : https://github.com/toml-lang/toml#user-content-comment


# MODKEY
# The modkey is used as a macro. Its main purpose is to be a central "control" key.
# We recommend using a modifier key such as Control, Alt or Super (Super would be best).
# To refer to the modkey you may use "$mod" in your bindings.
modkey = "Control"

# KEYBINDINGS
# This is the main section of this configuration. Every entry in this section will be bind to a command.

# KEYCODES
# Comfy uses the XKB standard for the keys, you can use "xev" to find what keycodes you can use. Comfy uses
# special classes for modifier keys, for example "Control" will be translated to "Control_L" and "Control_R".
# You can still use "Control_L" in your configuration.

# ENTRY
# To add entry use this syntax:
# "<keycode>(+<keycode>)*" = "<comfy_command> [<arguments>]"

[keybindings]
"$mod+Shift+Up" = "move_active_window_up"
"$mod+Shift+Down" = "move_active_window_down"
"$mod+Shift+Left" = "move_active_window_left"
"$mod+Shift+Right" = "move_active_window_right"

"$mod+Up" = "move_active_focus_up"
"$mod+Down" = "move_active_focus_down"
"$mod+Left" = "move_active_focus_left"
"$mod+Right" = "move_active_focus_right"

"$mod+k" = "set_insert_direction_up"
"$mod+j" = "set_insert_direction_down"
"$mod+h" = "set_insert_direction_left"
"$mod+l" = "set_insert_direction_right"

"$mod+Shift+n" = "put_active_window_to_stack"
"$mod+Shift+m" = "pop_window_from_stack"

"$mod+Shift+f" = "toggle_active_window_fullscreen"
"$mod+Shift+r" = "reload_config"

"$mod+Return" = "exec xfce4-terminal"
"$mod+q" = "close_active_window"
"$mod+Escape" = "terminate"