.TH COMFYWM 1 "DECEMBER 2018" Linux "User Manuals"
.SH NAME
Comfywm \- The comfiest window manager
.SH SYNOPSIS
.B comfywm
.SH DESCRIPTION
.B comfywm
A tiling window manager written in Rust using the Wayland protocol.
.SH FILES
.I /etc/comfywm/
.RS
The system wide configuration files path. For more details
on the configuration, please refer to the files themselves.
.RE
.I ~/.config/confywm
.RS
The user configuration path. Use this location to keep your preference.
.SH AUTHORS
Daniel Junior-Dubé <https://github.com/daniel-junior-dube>

Félix Chabot <https://github.com/chabam>
