use wlroots::SeatHandler as WLRSeatHandler;

/*
..####...######...####...######.
.##......##......##..##....##...
..####...####....######....##...
.....##..##......##..##....##...
..####...######..##..##....##...
................................
*/

pub struct SeatHandler;
impl WLRSeatHandler for SeatHandler {}
